### ISSUE TITLE
Specify authorship information in composer.json

### ISSUE THREAD

**Issue by legoktm** [cssjanus/php-cssjanus#15]
https://getcomposer.org/doc/04-schema.md#authors

forwarded from https://phabricator.wikimedia.org/T114580

**Comment by Krinkle** [comment]
Was fixed before this issue was created, in 870d3b1d970b9. Not yet released. Will do soon.

**Comment by Krinkle** [comment]
Done. https://github.com/cssjanus/php-cssjanus/releases/tag/v1.2.1
