### ISSUE TITLE
explicit start/end instead of global left/right

### ISSUE THREAD

**Issue by verdy-p** [cssjanus/php-cssjanus#17]
Instead of converting "*-left" and "*-right" properties (with conditional flags that still apply blindly to all CSS properties), you should support "-start" and "-end" properties to convert them to the appropriate "-left" or "-right" depeding on direction, for browsers that don't have such "*-start"/"*-end" support, without neceassirily changing all source "*-left" and "*-right" properties (as well as order of space-separated values in "margin" and "padding" when there are at least 3 values).

Another better way could also be to convert only these explicit properties:
- "*-left-ltr" to "*-left" in ltr context, or to "-right" in rtl context
- "*-right-ltr" to "*-right" in ltr context, or to "-left" in rtl context
- "*-left-rtl" to "*-right" in ltr context, or to "-right" in rtl context
- "*-right-ltr" to "*-left" in ltr context, or to "-left" in rtl context
- "margin-ltr: a b c [d]" to "margin: a b c [d]" in ltr context, or "margin: c b a [d]" in rtl context
- "margin-rtl: a b c [d]" to "margin: c b a [d]" in ltr context, or "margin: a b c [d]" in rtl context
- "padding-ltr: a b c [d]" to "margin: a b c [d]" in ltr context, or "margin: c b a [d]" in rtl context
- "padding-rtl: a b c [d]" to "margin: c b a [d]" in ltr context, or "margin: a b c [d]" in rtl context
- and similar...

**Comment by Krinkle** [comment]
(Note that this repo is a port, issues should generally be filed at <https://github.com/cssjanus/cssjanus/>)

The design of CSSJanus is to take a valid stylesheet written for LTR, and generate an RTL equivalent. It is against our design to introduce non-standard properties that require compilation. This means that CSSJanus must not be required to produce the LTR version, your source is the LTR version its raw form. It is also part of the design not to vary output by browsers, but to output only a single stylesheet.

As such, CSSJanus does not seem like the right place to convert `margin-start` to `margin-left/right` because CSSJanus cannot know during transformation, what the directionality will be of the content, which may be different from the directionality of the user interface.

When properties like `margin-block-start` become implemented in more browsers, you can start using them, and that will not require CSSJanus to transform it.

If you prefer to use margin-left/right only as fallback in older browser, we will need to find a way to make sure browsers ignore margin-left/right when margin-block-start exist. I do now know if that has been considered yet in the Web Platform standard.

Assuming that the fallback is considered, you can use CSSJanus for the fallback, like so:

```css
.example {
  margin-left: 10px; /* Fallback, flipped by CSSJanus */
  margin-block-start: 10px; /* Modern */
}
```

CSSJanus will not flip the `-start` property. As such, I do not understand yet what you are asking CSSJanus to offer.

I would like to continue your feature request, please create it at <https://github.com/cssjanus/cssjanus/>. I am interested in continuing this conversation.

**Comment by verdy-p** [comment]
2018-03-27 21:46 GMT+02:00 Timo Tijhof <notifications@github.com>:

> (Note that this repo is a port, issues should generally be filed at
> https://github.com/cssjanus/cssjanus/)
>
> The design of CSSJanus is to take a valid stylesheet written for LTR, and
> generate an RTL equivalent. It is against our design to introduce
> non-standard properties that require compilation.
>

You answer just quoted here is compeltely contradictiove, because of course
it does makje a compilation, but it does it "blindly", supposing that
everythingf that is specified on the "left" side witll become "right" and
vice versa. Adn this is not true. We don't have the filters we really need
for Bidi, and that require EXPLICIT indication of whever right should
remain right and left should remain left, and only "start" and "end" will
be swapped.

So you are efffecfively compiling a CSS source into another CSS, but
without knowing at all what it does. And in addition this is not sufficient
to "mirror"a layout, because we also need to adject the content as well
(images, or even characters must be replaced). And this is not just basic
mirroring, notably when there's some 3D effect or shadows: the
shadows/light will NOT move, some characters are mirrored in more complex
ways (e.g. with italic/slanted styles, look as what happens with comas,
question marks, and quotation marks)

Using explicit "start/end" markup in the source is the only solution to
produce the intended output. You'll compile it to generate CSS that will
sometimes "duplicate" styles using additional specifiers in selectors so
the CSS properties values can be different: you don't have just to replace
one property by another, you have to generate two properties from one, and
to generate for each one the necessary selectors.

Ideally we should also be able to use expressions in CSS property values,
such as
{
  property-name: (getDir() == 'ltr' ? "value if ltr" : "value if rtl")
}
But most browsers don't support expressions in CSS property values, and the
set of expressions/functions is also not portable. That's why we need a
proprocessing. Janus is not the only solution to preprocess a stylesheet
and generate the actual stylesheet that will be used by browsers. And there
are different CSS preprocesinng languages:
- one kind to be used on server-side so that browsers will use the
generated CSS directly (the server can use browser detection to tune the
result)
- the other king is client-side: no CSS is actually generated by the
server, but the client runs some javascript framework like jQuery to change
the document and generate the CSS it will render by inserting it within the
DOM.

The server-side solution is the most popular one as it offers greater
compatility and better evolutivity with more predictable results, and
faster response for thin clients (e.g. modest smartphones,
webTV/smartTV/IoT profiles, or viewing in very restricted UIs within apps
that don't want to integrate any Javascript engine and complex layout
engine, but use their own UI engine based on other paradigms, e.g. for
accessibility, or immersive 3D UI: the generated CSS and content must use a
much more reduced set of features in the "TinyCSS" profile and very small
subset of HTML; other non-visual rendering styles must also be workable,
notably rendering for audio only, and be able to "read" the UI in the
correct order which is compeltely independant of visual Bidi reordering,
but based on actual and more semantic start/end and not on visual
left/right...).

Some scripts have also their own requirements beyond just left/right
(notably for the vertical rendering, notably in Asian scripts, but as well
for Latin: start/end turns to become top/bottom, but without the mirroring,
or with more complex rules !

**Comment by Krinkle** [comment]
@verdy-p Thank you, but my statement was not contradictory. 

> The design of CSSJanus is to take a valid stylesheet written for LTR, and
 generate an RTL equivalent. It is against our design to introduce
 non-standard properties that require compilation.

CSSJanus uses standard properties as input from CSS. Developers write the stylesheet in LTR mode. This means that for the LTR "version", there is no compilation and no transformation needed. CSSJanus is not even activated. The original source code works _without_ CSSJanus.

For the RTL "version", CSSJanus is activated and it transforms properties where needed.

**Comment by verdy-p** [comment]
And that's why it does not work at all in RTL mode, and gives false results
almost everywhere once you have to process a *real* stylesheet for any
important project. It jsut works to translate a few styles for small
elements where the limitations are known. We still need someting else to
produce a usable page layout. In fact it offers little help as we can
already write stylesheets without Janus taking into account a single
direction attribute in selectors.
It does not work for adapting more complex things, such as changing the
content, tuning the effective miroring and graphical effects.
What I was asking we just to allow "start/end" to be used as moire
selective hints than just basic left/right distinction.
If Janus can do this transform for RTL, I don't see why it cannot do this
as well for LTR, and in that case translate "start/end" on both cases into
"left/right" or "right/left". This would make Janus more productful, even
if it will still not solve all problems. For replacing contents, we could
as well have custom selectors properties that will be translated into
standard selectors and standard CSS properties (notably by generating
"display:none" to hide the non relevant context in the generated
stylesheets or by adding instead contents, or changing background images or
illustration images with an implicit orientation in their graphic design,
or chaning the glyphs without changing the shadows/light sources/wind
directions: some parts of the image may be oriented but not all parts and
we need to switch the image completely, not just mirror it: this applies
for example for designing buttons with 3D effects, only the relative order
of buttons and their alignement/margins is swappable using basic right/left
reversal, or using reordering of margin/padding values when there's at
least 3 values given)

I've done adaptations of LTR-only websites to Bidi: each time it required
much more work that this basic transform and there were exceptions
everywhere to the simple automatic swap of left vs. right, which simply did
not work at all. As well, it frequently required using the "Bidi isolation"
mechanism (notably in multilingual pages: don't assume that all pages are
monolingual, almost all actual languages that use RTL scripts are actually
using multiple scripts with really directional contents where "isolation"
is the only safe solution; isolation concerns text of course, with Unicode
Bidi, but also styles and graphics for lots of details that most
English-only programmers do not suspect as this seems implicit for them
under frequent false assumptions, not easy to predict for them if they
actualyl don't know any RTL-written language or don't know how Bidi
contents are read and understood and how to best tune the orientation for
Bidi languages and better readability/usability.).



2018-03-27 23:41 GMT+02:00 Timo Tijhof <notifications@github.com>:

**Comment by verdy-p** [comment]
This is exactly within wikis that I have found various problems. Mediawiki
allows solving this NOT by using this trick but by using custom styles
making explicit uses of the direction in selectors, to override the false
guesses made by Janus. Any anyway Janus is not used as much as you say in
Mediawiki, never for the whole page layout (each time it has been tried it
was failing), but for a few small specific inline elements generated by a
few gadgets of small elements. It is NEVER used for the editable wiki
content itself and never used for the global page layout: it just processes
very small css style sheets used in a few extensions!


2018-03-28 1:24 GMT+02:00 Timo Tijhof <notifications@github.com>:

**Comment by Krinkle** [comment]
Your statement is simply incorrect. CSSJanus flips the layouts of all skins, page layouts and user interfaces that currently exist in Wikimedia source control. Including Vector skin, MobileFrontend, special pages, VisualEditor, OOUI and more.

Have a nice day.
