### ISSUE TITLE
Update implementation to 1.3.0 spec

### ISSUE THREAD

**Issue by Krinkle** [cssjanus/php-cssjanus#20]
Last sync was 1.2.0.

Notes at <https://github.com/cssjanus/cssjanus/blob/v1.3.1/History.md#release-history>.

Nominal changes:
* Fix unintended flipping of selectors containing a backslash (YairRand).
* Fix bug where transform didn't flip on lines without semicolon (YairRand).

**Comment by reedy** [comment]
> * Fix unintended flipping of selectors containing a backslash (YairRand).
> * Fix bug where transform didn't flip on lines without semicolon (YairRand).

#24 and #25 bring these in
