### ISSUE TITLE
the script not works on large file

### ISSUE THREAD

**Issue by yanivz** [cssjanus/php-cssjanus#28]
i have a large css file that is not being transformed

**Comment by Krinkle** [comment]
* Which PHP version.
* Which version of CSSJanus, and how is it installed (Composer?)
* What is the value of `ini_get( 'memory_limit' )`.
* Can you upload a copy of a file that is not working (e.g. via <https://gist.github.com>) that I can use to reproduce the issue?

**Comment by ramtin2025** [comment]
> i have a large css file that is not being transformed

Try this: [Using mbstring (improve performance on localhost)](https://github.com/cssjanus/php-cssjanus/pull/13)

**Comment by yanivz** [comment]
files size 382 KB
 i dont know use gist
i use like this
require_once(BX_DIRECTORY_PATH_PLUGINS_PUBLIC .'/php-cssjanus/src/CSSJanus.php');
$sCss = CSSJanus::transform($sCss);

> * Which PHP version. **7.2**
> * Which version of CSSJanus, and how is it installed (Composer?) **latest**
> * What is the value of `ini_get( 'memory_limit' )`. **128M**
> * Can you share an example that is not working? E.g. short script that calls CSSJanus (which method + parameters), as well as a copy of a file that is not working for you (e.g. via https://gist.github.com.
> 
> Thanks :)

**Comment by Krinkle** [comment]
@yanivz I'm sorry but without a copy of a file that causes the problem, I cannot help. You can copy the contents to a Gist to share it. Or, upload it elsewhere and share the link it :)
