### ISSUE TITLE
Calc values are not flipped

### ISSUE THREAD

**Issue by jdlrobson** [cssjanus/php-cssjanus#35]
https://cssjanus.github.io/#input/.sidebar-toc%20%7B%0A%09padding%3A%2010px%20calc(15px%20%2B%200.75em)%2010px%2012px%3B%0A%7D%0A

Expected:
```
.sidebar-toc {
	padding: 10px calc(15px + 0.75em) 10px 12px;
}

```
should be flipped to

```
.sidebar-toc {
	padding: 10px 12px 10px calc(15px + 0.75em);
}

```
Presumably, the calc trips it?

**Comment by Krinkle** [comment]
Tracked upstream for the reference implementation at https://github.com/cssjanus/cssjanus/issues/82. Patch welcome there!

(It'll be ported to PHP as part of the release process after upstream release)
